ProyectoFinal_NatalinViquez/Models/ErrorViewModel.cs
using System;

namespace ProyectoFinal_natalinviquez.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoFinal_NatalinViquez/Models/Maquina.cs
using Newtonsoft.Json;

namespace ProyectoFinal_natalinviquez.Models
{
    public class Maquina
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        public int cantidadProductoPorHora { get; set; }


        public int costoEnColones { get; set; }


        public int costoPorHora { get; set; }


        public double probabilidadFallo { get; set; }


        public string garantia { get; set; }
    
        public bool estado { get; set; }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

ProyectoFinal_NatalinViquez/Models/Producto.cs
using Newtonsoft.Json;

namespace ProyectoFinal_natalinviquez.Models
{
    public class Producto
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }
        public string Nombre { get; set; }

        public int Precio { get; set; }

    }
}

ProyectoFinal_NatalinViquez/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProyectoFinal_natalinviquez.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoFinal_natalinviquez.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoFinal_NatalinViquez/Controllers/MaquinasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Documents.Client;
using ProyectoFinal_natalinviquez.Models;
using ProyectoFinal_natalinviquez.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoFinal_natalinviquez.Controllers
{
    public class MaquinasController : Controller
    {

        ServiceCosmosDb service;
        public MaquinasController(ServiceCosmosDb service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult ListaMaquinas()
        {
            return View(this.service.GetMaquinas());
        }

        public IActionResult CreateMaquina()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(String accion)
        {
            await this.service.CrearBbddAsync();
            await this.service.CrearColeccionAsync();
          
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateMaquina(Maquina peli)
        {
            var random = new Random(Environment.TickCount);
            peli.probabilidadFallo = random.Next(0, 5);
            peli.estado = true;
            await this.service.InsertarMaquina(peli);
            return RedirectToAction("ListaMaquinas");
        }

        public async Task<IActionResult> Delete(String id)
        {
            await this.service.EliminarMaquina(id);
            return RedirectToAction("ListaMaquinas");
        }

        public async Task<IActionResult> Editar(String id)
        {
            return View(await this.service.FindPeliculaAsyn(id));
        }
        [HttpPost]
        public async Task<IActionResult> Editar(Maquina peli)
        {
            await this.service.ModificarMaquina(peli);
            return RedirectToAction("ListaMaquinas");
        }
    }
}

ProyectoFinal_NatalinViquez/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinal_natalinviquez.Models;
using ProyectoFinal_natalinviquez.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoFinal_natalinviquez.Controllers
{
    public class ProductoController : Controller
    {

        private  ICosmosDBService _cosmosDbService;
        public ProductoController(ICosmosDBService cosmosDbService)
        {
            _cosmosDbService = cosmosDbService;
        }


        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult ListaProducto()
        {
            List<Producto> lista = ListaProducto2().Result;
            return View(lista);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }
 
        [HttpGet]
        [Route("ListaProducto")]
        public async Task<List<Producto>> ListaProducto2()
        {
            try
            {
                return (await _cosmosDbService.GetItemsAsync("SELECT * FROM c")).ToList(); ;
            }
            catch
            {
                throw;
            }
        }


        [HttpPost]
        public async Task<IActionResult> CreateProduct(Producto item)
        {
            try
            {
                item.Id = Guid.NewGuid().ToString();
                await _cosmosDbService.AddItemAsync(item);
            }
            catch { throw; }
            return RedirectToAction("ListaProducto");
        }


    }
}

ProyectoFinal_NatalinViquez/Controllers/SimulacionController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProyectoFinal_natalinviquez.Controllers
{
    public class SimulacionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProyectoFinal_NatalinViquez/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoFinal_NatalinViquez/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFinal_NatalinViquez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ProyectoFinal_NatalinViquez</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProyectoFinal_NatalinViquez - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ProyectoFinal_NatalinViquez/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido!!</h1>

    <img src="@Url.Content("https://www.doquaformacion.com/wp-content/uploads/2020/09/rellotge.jpg")" alt="imgf"/> 
</div>

ProyectoFinal_NatalinViquez/Views/Maquinas/CreateMaquina.cshtml
@model ProyectoFinal_natalinviquez.Models.Maquina
@{
    ViewData["Title"] = "CreateMaquina";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear Maquina</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateMaquina">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidadProductoPorHora" class="control-label"></label>
                <input asp-for="cantidadProductoPorHora" class="form-control" />
                <span asp-validation-for="cantidadProductoPorHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="costoEnColones" class="control-label"></label>
                <input asp-for="costoEnColones" class="form-control" />
                <span asp-validation-for="costoEnColones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="costoPorHora" class="control-label"></label>
                <input asp-for="costoPorHora" class="form-control" />
                <span asp-validation-for="costoPorHora" class="text-danger"></span>
            </div>
   
            <div class="form-group">
                <label asp-for="garantia" class="control-label"></label>
                <input asp-for="garantia" class="form-control" />
                <span asp-validation-for="garantia" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="CreateMaquina" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ProyectoFinal_NatalinViquez/Views/Maquinas/Editar.cshtml
@model ProyectoFinal_natalinviquez.Models.Maquina
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
              <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidadProductoPorHora" class="control-label"></label>
                <input asp-for="cantidadProductoPorHora" class="form-control" />
                <span asp-validation-for="cantidadProductoPorHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="costoEnColones" class="control-label"></label>
                <input asp-for="costoEnColones" class="form-control" />
                <span asp-validation-for="costoEnColones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="costoPorHora" class="control-label"></label>
                <input asp-for="costoPorHora" class="form-control" />
                <span asp-validation-for="costoPorHora" class="text-danger"></span>
            </div>
   
            <div class="form-group">
                <label asp-for="garantia" class="control-label"></label>
                <input asp-for="garantia" class="form-control" />
                <span asp-validation-for="garantia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoFinal_NatalinViquez/Views/Maquinas/Index.cshtml
@model IEnumerable<ProyectoFinal_natalinviquez.Models.Maquina>
@{
    ViewData["Title"] = "Lista de maquinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row" style="margin-left:auto;  margin-right: auto;">
        <img src="@Url.Content("https://www.ceupe.mx/images/easyblog_articles/305/Imagen-1.jpg")" width="532px" style="margin-left:auto;  margin-right: auto;" alt="imgf"/> 
    </div>
    <hr />

    <div class="row">

        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="ListaMaquinas" asp-controller="Maquinas">Ver maquinas</a>
        </div>

         <div class="col-sm-6">
            <a class="btn btn-success d-block" name="accion" asp-action="CreateMaquina" asp-controller="Maquinas">Agregar maquina</a>
        </div>
    </div>


     <div class="row">

     

    </div>
</div>

ProyectoFinal_NatalinViquez/Views/Maquinas/ListaMaquinas.cshtml
@model IEnumerable<ProyectoFinal_natalinviquez.Models.Maquina>
@{
    ViewData["Title"] = "ListaMaquinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista de maquinas</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidadProductoPorHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.costoEnColones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.costoPorHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.probabilidadFallo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.garantia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estado)
            </th>
            <th></th>
        </tr>
    </thead>
      <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidadProductoPorHora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.costoEnColones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.costoPorHora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.probabilidadFallo)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.garantia)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Editar", new { id=item.Id }) |
                @Html.ActionLink("Details", "Detalles", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoFinal_NatalinViquez/Views/Producto/CreateProduct.cshtml
@model ProyectoFinal_natalinviquez.Models.Producto

@{
    ViewData["Title"] = "CreateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Crear Producto</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
           
         
            <div class="form-group">
                <input type="submit" value="CreateProduct" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ProyectoFinal_NatalinViquez/Views/Producto/Index.cshtml
@model  IEnumerable<ProyectoFinal_natalinviquez.Models.Producto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <div class="row" style="margin-left:auto;  margin-right: auto;">
        <img src="@Url.Content("https://www.combinatoria.com.ar/wp-content/uploads/2018/09/Indicadores-ecommerce-vender-online1170x550-900x.png")" width="532px" style="margin-left:auto;  margin-right: auto;" alt="imgf"/> 
    </div>
    <hr />
<div class="container">

    <div class="row">

        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="ListaProducto" asp-controller="Producto">Ver Productos</a>
        </div>

         <div class="col-sm-6">
            <a class="btn btn-success d-block" name="accion" asp-action="CreateProduct" asp-controller="Producto">Agregar Producto</a>
        </div>
    </div>


     <div class="row">

     

    </div>
</div>

ProyectoFinal_NatalinViquez/Views/Producto/ListaProducto.cshtml
@model  IEnumerable<ProyectoFinal_natalinviquez.Models.Producto>
@{
    ViewData["Title"] = "ListaProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ListaProducto</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            
            <th></th>
        </tr>
    </thead>
      <tbody>
          
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
       
            <td>
                @Html.ActionLink("Edit", "Editar", new { id=item.Id }) |
                @Html.ActionLink("Details", "Detalles", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoFinal_NatalinViquez/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFinal_natalinviquez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!--
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoFinal_natalinviquez</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>-->
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Maquinas" asp-action="Index">Maquinas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
       
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simulacion" asp-action="Index">Ejecutar simulacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProyectoFinal_natalinviquez - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ProyectoFinal_NatalinViquez/Views/Simulacion/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <img src="@Url.Content("https://editme.co.za/wp-content/uploads/2016/05/loader.gif")" alt="imgf"/> 
</div>